-- This query is listing dashboard usage from Looker's internal content_usage table
-- This table is located at Explore > System Activity > Content Usage
-- In this feature, there is a "Contage Usage" section with fields.
-- The query below uses such fields and it is generated by Looker (I just copied it from the SQL tab of the Explore)

SELECT
    content_usage.content_id AS `content_usage.content_id`,
    look.id AS `look.id`,

        CAST(content_usage.content_id AS SIGNED)
       AS `content_usage.content_id_as_number`,
    dashboard.id AS `dashboard.id`,
        (CASE WHEN (content_usage.content_type = 'look' AND look.id IS NULL) THEN 'Yes' ELSE 'No' END) AS `content_usage.look_deleted`,
        (CASE WHEN (content_usage.content_type = 'dashboard' AND content_usage.content_id NOT LIKE '%::%' AND dashboard.id IS NULL) THEN 'Yes' ELSE 'No' END) AS `content_usage.dashboard_deleted`,
    COALESCE(look.title,dashboard.TITLE,content_usage.content_id)  AS `content_usage.content_title`,
        (DATE(content_usage.LAST_ACCESSED_AT )) AS `content_usage.last_accessed_date`,
    content_usage.other_count AS `content_usage.other_count`,
    CASE WHEN content_usage.content_type =

              "homepage" THEN "board"

          ELSE content_usage.content_type END  AS `content_usage.content_type`,
    COALESCE(SUM(content_usage.schedule_count), 0) AS `content_usage.schedule_total`,
    COALESCE(SUM(content_usage.favorite_count), 0) AS `content_usage.favorites_total`
FROM (SELECT * FROM content_usage
                    WHERE content_type != 'explore'
                    AND
                    NOT ((content_type = 'look' OR content_type = 'homepage')
                          AND

                            content_id NOT REGEXP '^[0-9]+$'

                          ))  AS content_usage
LEFT JOIN dashboard ON
        content_usage.content_id = CAST(dashboard.id AS CHAR)

       AND (CASE WHEN content_usage.content_type =

              "homepage" THEN "board"

          ELSE content_usage.content_type END) LIKE 'dashboard'
LEFT JOIN look ON
        content_usage.content_id = CAST(look.id AS CHAR)

       AND (CASE WHEN content_usage.content_type =

              "homepage" THEN "board"

          ELSE content_usage.content_type END) LIKE 'look'
WHERE (CASE WHEN content_usage.content_type =

              "homepage" THEN "board"

          ELSE content_usage.content_type END ) = 'dashboard' AND (NOT ((content_usage.content_type = 'dashboard' AND content_usage.content_id NOT LIKE '%::%' AND dashboard.id IS NULL)) OR ((content_usage.content_type = 'dashboard' AND content_usage.content_id NOT LIKE '%::%' AND dashboard.id IS NULL)) IS NULL) AND (NOT ((content_usage.content_type = 'look' AND look.id IS NULL)) OR ((content_usage.content_type = 'look' AND look.id IS NULL)) IS NULL)
GROUP BY
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
ORDER BY
    8 DESC
LIMIT 500